/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_session_post"];
        /** Logout */
        delete: operations["logout_api_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/journals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Journals */
        get: operations["journals_api_journals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/controls/{control}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Controls */
        post: operations["controls_api_controls__control__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream */
        get: operations["stream_api_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execution/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quarantine */
        get: operations["quarantine_api_execution_quarantine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execution/quarantine/{quarantine_id}/redrive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redrive */
        post: operations["redrive_api_execution_quarantine__quarantine_id__redrive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ControlCommand */
        ControlCommand: {
            /** Active */
            active: boolean;
            /** Expected Version */
            expected_version: number;
            /** Reason */
            reason: string;
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
        };
        /** Controls */
        Controls: {
            /** Version */
            version: number;
            /** Entry Halt */
            entry_halt: boolean;
            /** Full Kill */
            full_kill: boolean;
        };
        /**
         * EventRecord
         * @description An outbox event. Feeds list the newest (highest sequence) first; not a cursor.
         */
        EventRecord: {
            /** Sequence */
            sequence: number;
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /** Aggregate Id */
            aggregate_id: string;
            /** Aggregate Version */
            aggregate_version: number;
            /** Correlation Id */
            correlation_id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Recorded At */
            recorded_at: string;
            /** Schema Version */
            schema_version: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Integration */
        Integration: {
            /** Name */
            name: string;
            /**
             * Status
             * @constant
             */
            status: "NOT_CONFIGURED";
        };
        /**
         * JournalRecord
         * @description A committed Ledger journal of the challenge portfolio.
         */
        JournalRecord: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Facts */
            facts: {
                [key: string]: unknown;
            };
        };
        /** Login */
        Login: {
            /**
             * Key
             * Format: password
             */
            key: string;
        };
        /** Overview */
        Overview: {
            portfolio: components["schemas"]["PortfolioSnapshot"];
            /**
             * Mode
             * @constant
             */
            mode: "OBSERVE";
            /**
             * Risk Profile
             * @constant
             */
            risk_profile: "BALANCED";
            controls: components["schemas"]["Controls"];
            /** Strategies */
            strategies: components["schemas"]["Strategy"][];
            /** Integrations */
            integrations: components["schemas"]["Integration"][];
            regime: components["schemas"]["RegimeReadiness"];
            /**
             * Execution Enabled
             * @constant
             */
            execution_enabled: false;
        };
        /** PortfolioSnapshot */
        PortfolioSnapshot: {
            /** Id */
            id: string;
            /** Version */
            version: number;
            /**
             * Currency
             * @constant
             */
            currency: "USD";
            /**
             * Environment
             * @enum {string}
             */
            environment: "ACTIVE_PAPER" | "SHADOW";
            /** Capital */
            capital: string;
            /** Cash */
            cash: string;
            /** Realized Pnl */
            realized_pnl: string;
            /** Fees */
            fees: string;
            /**
             * Valuation Status
             * @enum {string}
             */
            valuation_status: "NO_MARKS" | "CASH_ONLY";
            /** Equity */
            equity: string | null;
            /** Positions */
            positions: components["schemas"]["Position"][];
        };
        /** Position */
        Position: {
            /** Instrument */
            instrument: string;
            /** Scope */
            scope: string;
            /** Quantity */
            quantity: string;
            /** Cost Basis */
            cost_basis: string;
        };
        /**
         * QuarantineRecord
         * @description An open execution quarantine entry and its receipt identity (SHADOW fixtures only).
         *
         *     A null portfolio_id means the receipt could not be attributed, which blocks new
         *     reservations for every portfolio. Redrive with the current version.
         */
        QuarantineRecord: {
            /** Id */
            id: string;
            /** Receipt Id */
            receipt_id: string;
            /** Portfolio Id */
            portfolio_id: string | null;
            /**
             * Reason
             * @enum {string}
             */
            reason: "CONFLICTING_DUPLICATE" | "UNSUPPORTED_REVISION" | "UNKNOWN_ACCOUNT" | "ORPHAN" | "OUT_OF_BOUNDS" | "LEDGER_REJECTED";
            /** Detail */
            detail: string;
            /** Version */
            version: number;
            /** Created At */
            created_at: string;
            /** Adapter Id */
            adapter_id: string;
            /** Adapter Account Id */
            adapter_account_id: string;
            /** Execution Id */
            execution_id: string;
            /** Revision */
            revision: number;
            /** Order Id */
            order_id: string;
        };
        /** RedriveCommand */
        RedriveCommand: {
            /** Expected Version */
            expected_version: number;
            /** Reason */
            reason: string;
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
        };
        /**
         * RedriveResult
         * @description Outcome of a quarantine redrive. A repeated command_id returns the recorded outcome.
         */
        RedriveResult: {
            /** Quarantine Id */
            quarantine_id: string;
            /** Receipt Id */
            receipt_id: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "APPLIED" | "STILL_QUARANTINED";
            /**
             * Status
             * @enum {string}
             */
            status: "OPEN" | "RESOLVED";
            /** Version */
            version: number;
            /** Reason */
            reason: ("CONFLICTING_DUPLICATE" | "UNSUPPORTED_REVISION" | "UNKNOWN_ACCOUNT" | "ORPHAN" | "OUT_OF_BOUNDS" | "LEDGER_REJECTED") | null;
            /** Journal Id */
            journal_id: string | null;
        };
        /** RegimeReadiness */
        RegimeReadiness: {
            /**
             * Status
             * @constant
             */
            status: "NOT_READY";
            /** Reason */
            reason: string;
        };
        /** Strategy */
        Strategy: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Status */
            status: string;
            /** Implementation */
            implementation: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    overview_api_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    journals_api_journals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalRecord"][];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRecord"][];
                };
            };
        };
    };
    controls_api_controls__control__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                control: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    quarantine_api_execution_quarantine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarantineRecord"][];
                };
            };
        };
    };
    redrive_api_execution_quarantine__quarantine_id__redrive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quarantine_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedriveCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedriveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
