/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_session_post"];
        /** Logout */
        delete: operations["logout_api_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/journals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Journals */
        get: operations["journals_api_journals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/controls/{control}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Controls */
        post: operations["controls_api_controls__control__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/dead-letters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dead Letters */
        get: operations["dead_letters_api_jobs_dead_letters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/redrive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redrive
         * @description Requeue a dead letter with its identity; audited as JOB_REDRIVEN in the outbox.
         */
        post: operations["redrive_api_jobs__job_id__redrive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream */
        get: operations["stream_api_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ControlCommand */
        ControlCommand: {
            /** Active */
            active: boolean;
            /** Expected Version */
            expected_version: number;
            /** Reason */
            reason: string;
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
        };
        /** Controls */
        Controls: {
            /** Version */
            version: number;
            /** Entry Halt */
            entry_halt: boolean;
            /** Full Kill */
            full_kill: boolean;
        };
        /**
         * EventRecord
         * @description An outbox event. Feeds list the newest (highest sequence) first; not a cursor.
         */
        EventRecord: {
            /** Sequence */
            sequence: number;
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /** Aggregate Id */
            aggregate_id: string;
            /** Aggregate Version */
            aggregate_version: number;
            /** Correlation Id */
            correlation_id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Recorded At */
            recorded_at: string;
            /** Schema Version */
            schema_version: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Integration */
        Integration: {
            /** Name */
            name: string;
            /**
             * Status
             * @constant
             */
            status: "NOT_CONFIGURED";
        };
        /**
         * JobCommandResult
         * @description The job's version after an audited command, or the recorded one on replay.
         */
        JobCommandResult: {
            /** Job Id */
            job_id: string;
            /** Version */
            version: number;
        };
        /**
         * JobRecord
         * @description A durable job. Dead letters are jobs in state DEAD; a redrive keeps id and keys.
         */
        JobRecord: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            job_class: components["schemas"]["WorkClass"];
            /** Scope */
            scope: string;
            /** Occurrence Key */
            occurrence_key: string;
            /** Correlation Id */
            correlation_id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Input Version */
            input_version: number | null;
            /** Priority */
            priority: number;
            state: components["schemas"]["JobState"];
            /** Version */
            version: number;
            /** Attempts */
            attempts: number;
            /** Max Attempts */
            max_attempts: number;
            /** Redrives */
            redrives: number;
            /** Fencing Token */
            fencing_token: number;
            /** Lease Owner */
            lease_owner: string | null;
            /** Lease Expires At */
            lease_expires_at: string | null;
            /** Scheduled At */
            scheduled_at: string;
            /** Available At */
            available_at: string;
            /** Deadline */
            deadline: string | null;
            /** Terminal Reason */
            terminal_reason: string | null;
            /** Last Error */
            last_error: string | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /**
         * JobState
         * @enum {string}
         */
        JobState: "QUEUED" | "RUNNING" | "SUCCEEDED" | "DEAD" | "EXPIRED";
        /**
         * JournalRecord
         * @description A committed Ledger journal of the challenge portfolio.
         */
        JournalRecord: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Facts */
            facts: {
                [key: string]: unknown;
            };
        };
        /** Login */
        Login: {
            /**
             * Key
             * Format: password
             */
            key: string;
        };
        /** Overview */
        Overview: {
            portfolio: components["schemas"]["PortfolioSnapshot"];
            /**
             * Mode
             * @constant
             */
            mode: "OBSERVE";
            /**
             * Risk Profile
             * @constant
             */
            risk_profile: "BALANCED";
            controls: components["schemas"]["Controls"];
            /** Strategies */
            strategies: components["schemas"]["Strategy"][];
            /** Integrations */
            integrations: components["schemas"]["Integration"][];
            regime: components["schemas"]["RegimeReadiness"];
            /**
             * Execution Enabled
             * @constant
             */
            execution_enabled: false;
        };
        /** PortfolioSnapshot */
        PortfolioSnapshot: {
            /** Id */
            id: string;
            /** Version */
            version: number;
            /**
             * Currency
             * @constant
             */
            currency: "USD";
            /**
             * Environment
             * @enum {string}
             */
            environment: "ACTIVE_PAPER" | "SHADOW";
            /** Capital */
            capital: string;
            /** Cash */
            cash: string;
            /** Realized Pnl */
            realized_pnl: string;
            /** Fees */
            fees: string;
            /**
             * Valuation Status
             * @enum {string}
             */
            valuation_status: "NO_MARKS" | "CASH_ONLY";
            /** Equity */
            equity: string | null;
            /** Positions */
            positions: components["schemas"]["Position"][];
        };
        /** Position */
        Position: {
            /** Instrument */
            instrument: string;
            /** Scope */
            scope: string;
            /** Quantity */
            quantity: string;
            /** Cost Basis */
            cost_basis: string;
        };
        /** RedriveCommand */
        RedriveCommand: {
            /** Expected Version */
            expected_version: number;
            /** Reason */
            reason: string;
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
        };
        /** RegimeReadiness */
        RegimeReadiness: {
            /**
             * Status
             * @constant
             */
            status: "NOT_READY";
            /** Reason */
            reason: string;
        };
        /** Strategy */
        Strategy: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Status */
            status: string;
            /** Implementation */
            implementation: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkClass
         * @description Chapter 08 work classes. Reconciliation and monitoring are safety work.
         * @enum {string}
         */
        WorkClass: "RECONCILIATION" | "MONITORING" | "INGEST" | "ANALYSIS" | "RESEARCH";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    overview_api_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    journals_api_journals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalRecord"][];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRecord"][];
                };
            };
        };
    };
    controls_api_controls__control__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                control: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                state?: components["schemas"]["JobState"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dead_letters_api_jobs_dead_letters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"][];
                };
            };
        };
    };
    redrive_api_jobs__job_id__redrive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedriveCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCommandResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
