"""Deterministic generator for the synthetic fixture market dataset. NOT MARKET DATA.

``synthetic-us-equities-v1`` holds twelve fictional instruments, 380 FIXTURE_WEEKDAY_V1
sessions of unadjusted daily bars, point-in-time reference records and declared data-quality
traps. Every value comes from this module and one fixed seed. Integer SplitMix64 draws, Decimal
arithmetic under a pinned context, LF line endings and float-free formatting make the output
byte-identical across platforms and supported Python versions.

Regenerate with::

    uv run python -m aura.data.fixture_generator --out data/fixtures/market/synthetic-us-equities-v1

A change to any generated byte needs a new dataset version in a new directory; v1 is
immutable. See docs/adr/0024-synthetic-fixture-market-data.md.
"""

import argparse
import hashlib
import json
from collections.abc import Sequence
from dataclasses import dataclass, replace
from datetime import UTC, date, datetime, time, timedelta
from decimal import (
    ROUND_CEILING,
    ROUND_FLOOR,
    ROUND_HALF_EVEN,
    Context,
    Decimal,
    DivisionByZero,
    InvalidOperation,
    Overflow,
    localcontext,
)
from pathlib import Path
from typing import Final

DATASET_ID: Final = "synthetic-us-equities-v1"
DATASET_VERSION: Final = 1
MANIFEST_SCHEMA_VERSION: Final = 1
GENERATOR_MODULE: Final = "aura.data.fixture_generator"
GENERATOR_VERSION: Final = 1
SEED: Final = 20260923
PROVENANCE_CLASS: Final = "SYNTHETIC_FIXTURE"
PUBLISHER_ID: Final = "aura-synthetic-fixture"
CALENDAR_ID: Final = "FIXTURE_WEEKDAY_V1"
TIMEZONE: Final = "America/New_York"
UNIVERSE_ID: Final = "SYN_ALL_V1"
DEFAULT_OUT: Final = "data/fixtures/market/synthetic-us-equities-v1"
TEST_MODULE: Final = "tests/test_fixture_dataset.py"

INSTRUMENTS_FILE: Final = "instruments.csv"
SYMBOLS_FILE: Final = "symbol_history.csv"
UNIVERSE_FILE: Final = "universe_membership.csv"
BARS_FILE: Final = "bars_1d.csv"
ACTIONS_FILE: Final = "corporate_actions.csv"
README_FILE: Final = "README.md"
MANIFEST_FILE: Final = "manifest.json"
DATA_FILES: Final = (INSTRUMENTS_FILE, SYMBOLS_FILE, UNIVERSE_FILE, BARS_FILE, ACTIONS_FILE)

# FIXTURE_WEEKDAY_V1: weekdays minus these dates. It is not an exchange calendar.
FIRST_SESSION: Final = date(2024, 1, 2)
SESSION_COUNT: Final = 380
WARM_UP_SESSIONS: Final = 200
FIXTURE_HOLIDAYS: Final = tuple(
    date.fromisoformat(day)
    for day in (
        "2024-01-15",
        "2024-02-19",
        "2024-03-29",
        "2024-05-27",
        "2024-06-19",
        "2024-07-04",
        "2024-09-02",
        "2024-11-28",
        "2024-12-25",
        "2025-01-01",
        "2025-01-20",
        "2025-02-17",
        "2025-04-18",
        "2025-05-26",
        "2025-06-19",
        "2025-07-04",
    )
)

# Local America/New_York clock times. Stored instants are always UTC.
SESSION_OPEN: Final = time(9, 30)
SESSION_CLOSE: Final = time(16, 0)
PRE_OPEN_TIME: Final = time(8, 0)
NOTICE_TIME: Final = time(17, 0)
CORRECTION_TIME: Final = time(18, 0)
PUBLICATION_DELAY: Final = timedelta(minutes=15)
PROVISIONAL_DELAY: Final = timedelta(minutes=1)
LATE_DELIVERY_DELAY: Final = timedelta(minutes=20)

TICK: Final = Decimal("0.01")
_PRICE_QUANTUM: Final = Decimal("1E-10")
_RATE_QUANTUM: Final = Decimal("1E-12")
_MAX_ABS_RETURN: Final = Decimal("0.30")
_GAP_SCALE: Final = Decimal("0.35")
_RANGE_SCALE: Final = Decimal("0.45")
_VOLUME_NOISE: Final = Decimal("0.25")
_VOLUME_MOVE: Final = Decimal("6")
_VOLUME_FLOOR: Final = Decimal("0.2")

# Trap placement as (instrument number, 0-based session index).
LISTED_MID_PERIOD: Final = 10
LISTING_SESSION: Final = 120
LISTING_NOTICE_SESSION: Final = 116
LATE_REVISION: Final = (2, 232)
LATE_REVISION_LAG: Final = 3
PROVISIONAL: Final = (3, 241)
MISSING_SESSION: Final = (4, 250)
IMPOSSIBLE_OHLC: Final = (5, 256)
IDENTICAL_DUPLICATE: Final = (6, 262)
CONFLICTING_DUPLICATE: Final = (1, 268)
OUT_OF_ORDER: Final = (12, 274)
UNKNOWN_INSTRUMENT: Final = (13, 280)
RENAMED: Final = 7
RENAMED_SYMBOL: Final = "SYN7R"
RENAME_SESSION: Final = 290
RENAME_NOTICE_SESSION: Final = 285
SPLIT: Final = 6
SPLIT_SESSION: Final = 305
SPLIT_NOTICE_SESSION: Final = 295
SPLIT_ACTION_ID: Final = "ca-0001"
DELISTED: Final = 9
DELISTING_LAST_SESSION: Final = 330
DELISTING_NOTICE_SESSION: Final = 325
DELISTING_DECLINE: Final = (290, Decimal("-0.0040"))
STALE: Final = 8
STALE_LAST_SESSION: Final = 372

_MASK64: Final = (1 << 64) - 1
_GOLDEN_GAMMA: Final = 0x9E3779B97F4A7C15
_TWO_53: Final = Decimal(1 << 53)
_MARKET_STREAM: Final = 1
_SECTOR_STREAM: Final = 2
_RETURN_STREAM: Final = 3
_GAP_STREAM: Final = 4
_RANGE_STREAM: Final = 5
_VOLUME_STREAM: Final = 6

JSON = dict[str, object]


def _mix64(value: int) -> int:
    z = value & _MASK64
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & _MASK64
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & _MASK64
    return z ^ (z >> 31)


class SplitMix64:
    """SplitMix64 on Python integers, so every platform draws the same sequence."""

    def __init__(self, seed: int) -> None:
        self._state = seed & _MASK64

    def next_u64(self) -> int:
        self._state = (self._state + _GOLDEN_GAMMA) & _MASK64
        return _mix64(self._state)

    def normal(self) -> Decimal:
        """Irwin-Hall approximation: twelve 53-bit uniforms minus 6. Mean 0, variance 1."""
        total = 0
        for _ in range(12):
            total += self.next_u64() >> 11
        return Decimal(total - 6 * (1 << 53)) / _TWO_53


def _stream(*labels: int) -> SplitMix64:
    state = SEED
    for label in labels:
        state = _mix64((state + _GOLDEN_GAMMA + label) & _MASK64)
    return SplitMix64(state)


def _decimal_context() -> Context:
    return Context(
        prec=28,
        rounding=ROUND_HALF_EVEN,
        Emin=-999999,
        Emax=999999,
        traps=[InvalidOperation, DivisionByZero, Overflow],
    )


def _nth_sunday(year: int, month: int, n: int) -> date:
    first = date(year, month, 1)
    return first + timedelta(days=(6 - first.weekday()) % 7 + 7 * (n - 1))


def dst_period(year: int) -> tuple[date, date]:
    """US daylight-saving dates in force since 2007: second Sunday of March, first of November."""
    if year < 2007:
        raise ValueError("The fixture only models the US daylight-saving rule in force since 2007")
    return _nth_sunday(year, 3, 2), _nth_sunday(year, 11, 1)


def new_york_utc_offset(day: date) -> timedelta:
    """UTC offset of America/New_York on a day without a transition (never a Sunday)."""
    if day.weekday() == 6:
        raise ValueError("Transitions happen on Sundays; the fixture never stamps a Sunday")
    start, end = dst_period(day.year)
    return timedelta(hours=-4) if start <= day < end else timedelta(hours=-5)


def new_york_to_utc(day: date, clock: time) -> datetime:
    local = datetime.combine(day, clock, tzinfo=UTC)
    return local - new_york_utc_offset(day)


def fixture_sessions() -> tuple[date, ...]:
    holidays = frozenset(FIXTURE_HOLIDAYS)
    sessions: list[date] = []
    day = FIRST_SESSION
    while len(sessions) < SESSION_COUNT:
        if day.weekday() < 5 and day not in holidays:
            sessions.append(day)
        day += timedelta(days=1)
    for holiday in FIXTURE_HOLIDAYS:
        if holiday.weekday() >= 5 or not FIRST_SESSION < holiday < sessions[-1]:
            raise ValueError(f"Fixture holiday {holiday} must be a weekday inside the window")
    return tuple(sessions)


def instrument_id(number: int) -> str:
    return f"inst_syn_{number:04d}"


@dataclass(frozen=True)
class Segment:
    kind: str
    sessions: int
    drift: Decimal
    volatility: Decimal
    reversion: Decimal
    sector_volatility: Decimal
    sector_spread: Decimal
    idiosyncratic_scale: Decimal
    volume_factor: Decimal


def _segment(kind: str, sessions: int, *values: str) -> Segment:
    drift, volatility, reversion, sector_vol, spread, idio, volume = (Decimal(v) for v in values)
    return Segment(kind, sessions, drift, volatility, reversion, sector_vol, spread, idio, volume)


# Data-generating parameters for tests. They are not canonical regime classifications.
SEGMENTS: Final = (
    _segment("TREND", 50, "0.0020", "0.0070", "0", "0.0030", "0.0006", "1.0", "1.00"),
    _segment("RANGE_BOUND", 45, "0", "0.0060", "0.12", "0.0025", "0", "0.9", "0.85"),
    _segment("HIGH_VOLATILITY", 30, "0", "0.0220", "0", "0.0060", "0", "1.8", "1.70"),
    _segment("DRAWDOWN", 40, "-0.0055", "0.0120", "0", "0.0030", "0.0004", "1.3", "1.45"),
    _segment("TREND", 50, "0.0024", "0.0080", "0", "0.0035", "0.0008", "1.0", "1.10"),
    _segment("RANGE_BOUND", 45, "0", "0.0055", "0.12", "0.0025", "0", "0.9", "0.80"),
    _segment("HIGH_VOLATILITY", 30, "0", "0.0240", "0", "0.0065", "0", "1.8", "1.80"),
    _segment("DRAWDOWN", 40, "-0.0060", "0.0130", "0", "0.0030", "0.0004", "1.3", "1.50"),
    _segment("TREND", 50, "0.0018", "0.0070", "0", "0.0030", "0.0006", "1.0", "1.00"),
)

SECTORS: Final = ("Orbital Agriculture", "Cloud Weaving", "Tidal Clockworks", "Lantern Freight")


@dataclass(frozen=True)
class InstrumentSpec:
    number: int
    symbol: str
    security_type: str
    name: str
    sector: str
    listed_on: date | None
    initial_price: Decimal
    base_volume: int
    beta: Decimal
    factor_sector: int | None
    idiosyncratic_volatility: Decimal

    @property
    def instrument_id(self) -> str:
        return instrument_id(self.number)


def _equity(
    number: int, sector: int, listed: str | None, price: str, volume: int, beta: str, idio: str
) -> InstrumentSpec:
    return InstrumentSpec(
        number=number,
        symbol=f"SYN{number:02d}",
        security_type="EQUITY",
        name=f"Synthetic Fixture Equity {number:02d}",
        sector=SECTORS[sector],
        listed_on=None if listed is None else date.fromisoformat(listed),
        initial_price=Decimal(price),
        base_volume=volume,
        beta=Decimal(beta),
        factor_sector=sector,
        idiosyncratic_volatility=Decimal(idio),
    )


def _basket(
    number: int, code: str, sector: str, factor: int | None, listed: str, price: str, volume: int
) -> InstrumentSpec:
    return InstrumentSpec(
        number=number,
        symbol=f"SYN{code}",
        security_type="ETF",
        name=f"Synthetic Fixture Basket {code}",
        sector=sector,
        listed_on=date.fromisoformat(listed),
        initial_price=Decimal(price),
        base_volume=volume,
        beta=Decimal("1.00") if factor is None else Decimal("1.20"),
        factor_sector=factor,
        idiosyncratic_volatility=Decimal("0.002") if factor is None else Decimal("0.003"),
    )


INSTRUMENTS: Final = (
    _equity(1, 0, "2018-03-05", "42.18", 850_000, "1.00", "0.012"),
    _equity(2, 0, "2016-09-12", "118.40", 420_000, "0.85", "0.010"),
    _equity(3, 1, "2019-05-20", "27.35", 2_300_000, "1.30", "0.018"),
    _equity(4, 1, "2020-10-01", "64.90", 1_100_000, "1.15", "0.015"),
    _equity(5, 2, "2015-02-17", "88.25", 640_000, "0.90", "0.011"),
    _equity(6, 2, "2017-06-19", "182.60", 300_000, "1.05", "0.013"),
    _equity(7, 3, "2021-03-15", "15.72", 3_400_000, "1.40", "0.022"),
    _equity(8, 3, "2014-11-03", "53.10", 510_000, "0.75", "0.012"),
    _equity(9, 3, "2019-08-26", "21.45", 1_800_000, "1.25", "0.024"),
    _equity(10, 0, None, "24.00", 2_600_000, "1.20", "0.025"),
    _basket(11, "X1", "Multi-Sector Basket", None, "2012-04-02", "236.40", 5_200_000),
    _basket(12, "X2", "Cloud Weaving Basket", 1, "2013-01-14", "71.30", 1_900_000),
)

# Appears only in bars_1d.csv: the unknown-instrument trap.
UNKNOWN_SPEC: Final = InstrumentSpec(
    number=UNKNOWN_INSTRUMENT[0],
    symbol="",
    security_type="EQUITY",
    name="",
    sector="",
    listed_on=None,
    initial_price=Decimal("33.40"),
    base_volume=700_000,
    beta=Decimal("1.00"),
    factor_sector=None,
    idiosyncratic_volatility=Decimal("0.015"),
)

INSTRUMENT_COLUMNS: Final = (
    ("instrument_id", "Stable fixture instrument ID (inst_syn_NNNN); never reused."),
    ("security_type", "EQUITY, or ETF for a synthetic ETF-like basket."),
    ("name", "Fictional descriptive name."),
    ("sector", "Fictional sector; static in this fixture."),
    ("currency", "ISO 4217 currency code."),
    ("tick_size", "Minimum price increment, decimal string."),
    ("listed_on", "First session date (America/New_York)."),
    ("available_at", "When this reference record became known (UTC)."),
)
SYMBOL_COLUMNS: Final = (
    ("instrument_id", "Stable fixture instrument ID."),
    ("symbol", "Fictional ticker; always contains a digit, so it cannot be a US exchange ticker."),
    ("effective_from", "First session date the symbol applies (inclusive)."),
    (
        "effective_to",
        "First session date the symbol no longer applies (exclusive); empty while open. The end "
        "of a period becomes known with the row that replaces it.",
    ),
    ("reason", "LISTING or RENAME."),
    ("available_at", "When this assignment became known (UTC)."),
)
UNIVERSE_COLUMNS: Final = (
    ("universe_id", "Point-in-time universe identifier."),
    ("instrument_id", "Stable fixture instrument ID."),
    ("action", "ADD or REMOVE."),
    ("effective_from", "First session date the action applies (inclusive)."),
    ("reason", "INITIAL, LISTING or DELISTING."),
    ("available_at", "When the membership change became known (UTC)."),
)
BAR_COLUMNS: Final = (
    (
        "provider_record_id",
        "Publisher observation identity (MarketObservation.provider_record_id). Revisions of one "
        "bar share it.",
    ),
    (
        "revision",
        "Positive integer; a higher revision supersedes a lower one from its available_at.",
    ),
    ("instrument_id", "Stable fixture instrument ID."),
    ("interval_start", "Session open, 09:30 America/New_York, as a UTC instant."),
    ("interval_end", "Session close, 16:00 America/New_York, as a UTC instant; the event time."),
    ("open", "Unadjusted USD price with exactly two decimal places."),
    ("high", "Unadjusted USD price with exactly two decimal places."),
    ("low", "Unadjusted USD price with exactly two decimal places."),
    ("close", "Unadjusted USD price with exactly two decimal places."),
    ("volume", "Shares traded, positive integer."),
    ("adjustment_basis", "RAW: prices as traded, not adjusted for splits or dividends."),
    ("final", "true for a completed bar, false for a provisional one."),
    ("available_at", "Publication time declared by the synthetic publisher (UTC)."),
)
ADJUSTMENT_BASIS: Final = "RAW"
NULLABLE_COLUMNS: Final = frozenset({"effective_to"})
ACTION_COLUMNS: Final = (
    ("action_id", "Stable corporate-action identity."),
    ("instrument_id", "Stable fixture instrument ID."),
    ("action_type", "SPLIT."),
    ("ex_date", "First session date trading on the new share basis."),
    ("ratio_new", "New shares received per ratio_old shares held."),
    ("ratio_old", "Shares held before the action."),
    ("available_at", "Announcement time (UTC)."),
)


@dataclass(frozen=True)
class Bar:
    provider_record_id: str
    revision: int
    instrument_id: str
    session: date
    interval_start: datetime
    interval_end: datetime
    open: Decimal
    high: Decimal
    low: Decimal
    close: Decimal
    volume: int
    final: bool
    available_at: datetime

    def cells(self) -> tuple[str, ...]:
        return (
            self.provider_record_id,
            str(self.revision),
            self.instrument_id,
            _instant(self.interval_start),
            _instant(self.interval_end),
            _price(self.open),
            _price(self.high),
            _price(self.low),
            _price(self.close),
            str(self.volume),
            ADJUSTMENT_BASIS,
            "true" if self.final else "false",
            _instant(self.available_at),
        )


@dataclass(frozen=True)
class _Delivery:
    bar: Bar
    redelivery: bool = False
    tag: str = ""

    def order(self) -> tuple[datetime, bool, str, str, int]:
        return (
            self.bar.available_at,
            self.redelivery,
            self.bar.instrument_id,
            self.bar.provider_record_id,
            self.bar.revision,
        )


def _instant(moment: datetime) -> str:
    if moment.utcoffset() != timedelta(0):
        raise ValueError("Fixture instants must be UTC")
    return f"{moment:%Y-%m-%dT%H:%M:%S}Z"


def _price(value: Decimal) -> str:
    if value <= 0 or value != value.quantize(TICK):
        raise ValueError(f"Price {value} is not a positive multiple of the tick")
    return str(value.quantize(TICK))


def _tick(value: Decimal, rounding: str = ROUND_HALF_EVEN) -> Decimal:
    return value.quantize(TICK, rounding=rounding)


def _close_available(session: date) -> datetime:
    return new_york_to_utc(session, SESSION_CLOSE) + PUBLICATION_DELAY


def _make_bar(
    number: int,
    session: date,
    prices: tuple[Decimal, Decimal, Decimal, Decimal],
    volume: int,
) -> Bar:
    open_, high, low, close = prices
    if not (0 < low <= min(open_, close) and max(open_, close) <= high) or volume < 1:
        raise ValueError(f"Generated an invalid bar for {instrument_id(number)} on {session}")
    return Bar(
        provider_record_id=f"bar-{number:04d}-{session:%Y%m%d}",
        revision=1,
        instrument_id=instrument_id(number),
        session=session,
        interval_start=new_york_to_utc(session, SESSION_OPEN),
        interval_end=new_york_to_utc(session, SESSION_CLOSE),
        open=open_,
        high=high,
        low=low,
        close=close,
        volume=volume,
        final=True,
        available_at=_close_available(session),
    )


def _segment_by_session() -> tuple[Segment, ...]:
    expanded = tuple(segment for segment in SEGMENTS for _ in range(segment.sessions))
    if len(expanded) != SESSION_COUNT:
        raise ValueError("Process segments must cover every session exactly once")
    return expanded


def _factor_returns() -> tuple[list[Decimal], list[list[Decimal]]]:
    market_rng = _stream(_MARKET_STREAM)
    sector_rngs = [_stream(_SECTOR_STREAM, index) for index in range(len(SECTORS))]
    level = Decimal(100)
    market: list[Decimal] = []
    sectors: list[list[Decimal]] = [[] for _ in SECTORS]
    for segment in SEGMENTS:
        anchor = level
        for _ in range(segment.sessions):
            move = segment.drift + segment.volatility * market_rng.normal()
            if segment.reversion:
                move -= segment.reversion * (level / anchor - 1)
            move = move.quantize(_RATE_QUANTUM)
            market.append(move)
            level = (level * (1 + move)).quantize(_PRICE_QUANTUM)
            for index, rng in enumerate(sector_rngs):
                centre = Decimal(2 * index - (len(SECTORS) - 1)) / 2
                shock = segment.sector_spread * centre + segment.sector_volatility * rng.normal()
                sectors[index].append(shock.quantize(_RATE_QUANTUM))
    return market, sectors


def _active_sessions(spec: InstrumentSpec) -> range:
    first = LISTING_SESSION if spec.listed_on is None else 0
    last = {DELISTED: DELISTING_LAST_SESSION, STALE: STALE_LAST_SESSION}.get(
        spec.number, SESSION_COUNT - 1
    )
    return range(first, last + 1)


def _simulate(
    spec: InstrumentSpec,
    active: range,
    sessions: Sequence[date],
    segments: Sequence[Segment],
    market: Sequence[Decimal],
    sectors: Sequence[Sequence[Decimal]],
) -> list[Bar]:
    returns = _stream(_RETURN_STREAM, spec.number)
    gaps = _stream(_GAP_STREAM, spec.number)
    ranges = _stream(_RANGE_STREAM, spec.number)
    volumes = _stream(_VOLUME_STREAM, spec.number)
    previous = spec.initial_price
    bars: list[Bar] = []
    for index in active:
        segment = segments[index]
        idiosyncratic = spec.idiosyncratic_volatility * segment.idiosyncratic_scale
        move = spec.beta * market[index] + idiosyncratic * returns.normal()
        if spec.factor_sector is not None:
            move += sectors[spec.factor_sector][index]
        if spec.number == DELISTED and index >= DELISTING_DECLINE[0]:
            move += DELISTING_DECLINE[1]
        move = min(max(move, -_MAX_ABS_RETURN), _MAX_ABS_RETURN)
        spread = segment.volatility * abs(spec.beta) + idiosyncratic
        opening = previous * (1 + _GAP_SCALE * spread * gaps.normal())
        closing = previous * (1 + move)
        upper = max(opening, closing) * (1 + _RANGE_SCALE * spread * abs(ranges.normal()))
        lower = min(opening, closing) * (1 - _RANGE_SCALE * spread * abs(ranges.normal()))
        divisor = Decimal(2) if spec.number == SPLIT and index >= SPLIT_SESSION else Decimal(1)
        open_ = _tick(opening / divisor)
        close = _tick(closing / divisor)
        high = max(open_, close, _tick(upper / divisor, ROUND_CEILING))
        low = min(open_, close, _tick(lower / divisor, ROUND_FLOOR))
        noise = max(_VOLUME_FLOOR, 1 + _VOLUME_NOISE * volumes.normal())
        shares = (
            spec.base_volume * segment.volume_factor * noise * (1 + _VOLUME_MOVE * abs(move))
        ) * divisor
        volume = int(shares.quantize(Decimal(1), rounding=ROUND_HALF_EVEN))
        bars.append(_make_bar(spec.number, sessions[index], (open_, high, low, close), volume))
        previous = closing.quantize(_PRICE_QUANTUM)
    return bars


def _shifted(bar: Bar, ticks: int) -> Decimal:
    """A close different from bar.close that stays inside [low, high]."""
    for candidate in (bar.close - ticks * TICK, bar.close + ticks * TICK):
        if bar.low <= candidate <= bar.high and candidate != bar.close:
            return candidate
    raise ValueError(f"No room to shift the close of {bar.provider_record_id}")


@dataclass(frozen=True)
class _Build:
    sessions: tuple[date, ...]
    deliveries: tuple[_Delivery, ...]
    rows: dict[str, int]

    def tagged(self, tag: str) -> tuple[int, Bar]:
        row = self.rows[tag]
        return row, self.deliveries[row - 1].bar


def _deliveries(clean: dict[int, list[Bar]], unknown: Bar, sessions: Sequence[date]) -> _Build:
    index_of = {session: index for index, session in enumerate(sessions)}
    context_tags = {
        (MISSING_SESSION[0], MISSING_SESSION[1] - 1): "missing_session:previous",
        (MISSING_SESSION[0], MISSING_SESSION[1] + 1): "missing_session:next",
        (OUT_OF_ORDER[0], OUT_OF_ORDER[1] + 1): "out_of_order_delivery:next",
        (LISTED_MID_PERIOD, LISTING_SESSION): "mid_period_listing:first",
        (DELISTED, DELISTING_LAST_SESSION): "delisting:last",
        (RENAMED, RENAME_SESSION - 1): "ticker_rename:before",
        (RENAMED, RENAME_SESSION): "ticker_rename:after",
        (SPLIT, SPLIT_SESSION - 1): "unsupported_split:before",
        (SPLIT, SPLIT_SESSION): "unsupported_split:ex_date",
        (STALE, STALE_LAST_SESSION): "stale_tail:last",
    }
    out: list[_Delivery] = []
    for spec in INSTRUMENTS:
        for bar in clean[spec.number]:
            key = (spec.number, index_of[bar.session])
            if key == MISSING_SESSION:
                continue
            if key == IMPOSSIBLE_OHLC:
                if not bar.low < bar.high:
                    raise ValueError("The impossible-OHLC trap needs a bar with a price range")
                swapped = replace(bar, high=bar.low, low=bar.high)
                out.append(_Delivery(swapped, tag="impossible_ohlc"))
            elif key == PROVISIONAL:
                provisional = replace(
                    bar,
                    close=_shifted(bar, 3),
                    volume=bar.volume * 9 // 10,
                    final=False,
                    available_at=bar.interval_end + PROVISIONAL_DELAY,
                )
                next_session = sessions[key[1] + 1]
                final = replace(
                    bar, revision=2, available_at=new_york_to_utc(next_session, PRE_OPEN_TIME)
                )
                out.append(_Delivery(provisional, tag="provisional_then_final:provisional"))
                out.append(_Delivery(final, tag="provisional_then_final:final"))
            elif key == LATE_REVISION:
                corrected = _tick(bar.close * Decimal("1.015"))
                revised = replace(
                    bar,
                    revision=2,
                    high=max(bar.high, corrected),
                    low=min(bar.low, corrected),
                    close=corrected,
                    volume=bar.volume + bar.volume // 25,
                    available_at=new_york_to_utc(
                        sessions[key[1] + LATE_REVISION_LAG], CORRECTION_TIME
                    ),
                )
                out.append(_Delivery(bar, tag="late_revision:original"))
                out.append(_Delivery(revised, tag="late_revision:revised"))
            elif key == IDENTICAL_DUPLICATE:
                out.append(_Delivery(bar, tag="identical_duplicate:first"))
                out.append(_Delivery(bar, redelivery=True, tag="identical_duplicate:second"))
            elif key == CONFLICTING_DUPLICATE:
                conflicting = replace(bar, close=_shifted(bar, 7), volume=bar.volume + 12_500)
                out.append(_Delivery(bar, tag="conflicting_duplicate:first"))
                out.append(
                    _Delivery(conflicting, redelivery=True, tag="conflicting_duplicate:second")
                )
            elif key == OUT_OF_ORDER:
                delivered = new_york_to_utc(sessions[key[1] + 1], SESSION_CLOSE)
                late = replace(bar, available_at=delivered + LATE_DELIVERY_DELAY)
                out.append(_Delivery(late, tag="out_of_order_delivery:late"))
            else:
                out.append(_Delivery(bar, tag=context_tags.get(key, "")))
    out.append(_Delivery(unknown, tag="unknown_instrument"))
    ordered = tuple(sorted(out, key=_Delivery.order))
    rows = {d.tag: row for row, d in enumerate(ordered, start=1) if d.tag}
    if len(rows) != sum(1 for d in ordered if d.tag):
        raise ValueError("Delivery tags must be unique")
    return _Build(tuple(sessions), ordered, rows)


def _pre_open(day: date) -> datetime:
    return new_york_to_utc(day, PRE_OPEN_TIME)


def _notice(session: date) -> datetime:
    return new_york_to_utc(session, NOTICE_TIME)


def _listed_on(spec: InstrumentSpec, sessions: Sequence[date]) -> date:
    return sessions[LISTING_SESSION] if spec.listed_on is None else spec.listed_on


def _reference_available(spec: InstrumentSpec, sessions: Sequence[date]) -> datetime:
    if spec.listed_on is None:
        return _notice(sessions[LISTING_NOTICE_SESSION])
    return _pre_open(spec.listed_on)


def _instrument_rows(sessions: Sequence[date]) -> list[tuple[str, ...]]:
    return [
        (
            spec.instrument_id,
            spec.security_type,
            spec.name,
            spec.sector,
            "USD",
            str(TICK),
            _listed_on(spec, sessions).isoformat(),
            _instant(_reference_available(spec, sessions)),
        )
        for spec in INSTRUMENTS
    ]


def _symbol_rows(sessions: Sequence[date]) -> list[tuple[str, ...]]:
    rows: list[tuple[str, ...]] = []
    for spec in INSTRUMENTS:
        renamed = spec.number == RENAMED
        rows.append(
            (
                spec.instrument_id,
                spec.symbol,
                _listed_on(spec, sessions).isoformat(),
                sessions[RENAME_SESSION].isoformat() if renamed else "",
                "LISTING",
                _instant(_reference_available(spec, sessions)),
            )
        )
        if renamed:
            rows.append(
                (
                    spec.instrument_id,
                    RENAMED_SYMBOL,
                    sessions[RENAME_SESSION].isoformat(),
                    "",
                    "RENAME",
                    _instant(_notice(sessions[RENAME_NOTICE_SESSION])),
                )
            )
    return rows


def _universe_rows(sessions: Sequence[date]) -> list[tuple[str, ...]]:
    events: list[tuple[datetime, str, str, date, str]] = []
    for spec in INSTRUMENTS:
        if spec.listed_on is None:
            listed = sessions[LISTING_SESSION]
            available = _notice(sessions[LISTING_NOTICE_SESSION])
            events.append((available, spec.instrument_id, "ADD", listed, "LISTING"))
        else:
            available = _pre_open(sessions[0])
            events.append((available, spec.instrument_id, "ADD", sessions[0], "INITIAL"))
        if spec.number == DELISTED:
            available = _notice(sessions[DELISTING_NOTICE_SESSION])
            removed = sessions[DELISTING_LAST_SESSION + 1]
            events.append((available, spec.instrument_id, "REMOVE", removed, "DELISTING"))
    return [
        (UNIVERSE_ID, instrument, action, effective.isoformat(), reason, _instant(available))
        for available, instrument, action, effective, reason in sorted(events)
    ]


def _action_rows(sessions: Sequence[date]) -> list[tuple[str, ...]]:
    return [
        (
            SPLIT_ACTION_ID,
            instrument_id(SPLIT),
            "SPLIT",
            sessions[SPLIT_SESSION].isoformat(),
            "2",
            "1",
            _instant(_notice(sessions[SPLIT_NOTICE_SESSION])),
        )
    ]


def _csv(columns: Sequence[tuple[str, str]], rows: Sequence[Sequence[str]]) -> bytes:
    """Plain RFC 4180 subset: no quoting is ever needed, and only nullable columns are empty."""
    names = [name for name, _ in columns]
    lines = [",".join(names)]
    for row in rows:
        if len(row) != len(columns):
            raise ValueError("Row width does not match the header")
        for name, cell in zip(names, row, strict=True):
            plain = cell == cell.strip() and not any(ch in cell for ch in ',"\r\n')
            if not plain or (not cell and name not in NULLABLE_COLUMNS):
                raise ValueError(f"Cell {cell!r} in {name} is not a plain CSV value")
        lines.append(",".join(row))
    return ("\n".join(lines) + "\n").encode("ascii")


def _bar_json(row: int, bar: Bar, role: str) -> JSON:
    names = [name for name, _ in BAR_COLUMNS]
    record: JSON = {"file": BARS_FILE, "row": row, "role": role}
    record.update(zip(names, bar.cells(), strict=True))
    return record


def _row_json(
    file: str, row: int, columns: Sequence[tuple[str, str]], cells: Sequence[str], role: str
) -> JSON:
    record: JSON = {"file": file, "row": row, "role": role}
    record.update(zip((name for name, _ in columns), cells, strict=True))
    return record


def _scenario(
    scenario_id: str,
    kind: str,
    files: Sequence[str],
    instrument: str,
    session: date | None,
    description: str,
    handling: str,
    expectation: str,
    trap_rows: Sequence[int],
    records: Sequence[JSON],
    facts: JSON,
) -> JSON:
    return {
        "id": scenario_id,
        "kind": kind,
        "files": list(files),
        "instrument_id": instrument,
        "session_date": None if session is None else session.isoformat(),
        "description": description,
        "expected_handling": handling,
        "expectation": expectation,
        "trap_rows": {BARS_FILE: list(trap_rows)} if trap_rows else {},
        "records": list(records),
        "facts": facts,
        "covered_by": f"{TEST_MODULE}::test_trap_{scenario_id}",
    }


def _scenarios(build: _Build) -> list[JSON]:
    sessions = build.sessions
    symbol_rows = _symbol_rows(sessions)
    universe_rows = _universe_rows(sessions)
    instrument_rows = _instrument_rows(sessions)
    action_rows = _action_rows(sessions)

    def reference(
        file: str,
        rows: Sequence[tuple[str, ...]],
        columns: Sequence[tuple[str, str]],
        role: str,
        **match: str,
    ) -> JSON:
        names = [name for name, _ in columns]
        hits = [
            (row, cells)
            for row, cells in enumerate(rows, start=1)
            if all(cells[names.index(k)] == v for k, v in match.items())
        ]
        if len(hits) != 1:
            raise ValueError(f"Expected one {file} row matching {match}")
        return _row_json(file, hits[0][0], columns, hits[0][1], role)

    def bar(tag: str, role: str) -> tuple[int, Bar, JSON]:
        row, found = build.tagged(tag)
        return row, found, _bar_json(row, found, role)

    late_row, _, late_original = bar("late_revision:original", "revision_1")
    revised_row, _, late_revised = bar("late_revision:revised", "revision_2")
    prov_row, _, provisional = bar("provisional_then_final:provisional", "provisional")
    final_row, _, final = bar("provisional_then_final:final", "final")
    _, _, missing_previous = bar("missing_session:previous", "previous_session")
    _, _, missing_next = bar("missing_session:next", "next_session")
    impossible_row, _, impossible = bar("impossible_ohlc", "impossible")
    identical_rows = [bar(f"identical_duplicate:{part}", part) for part in ("first", "second")]
    conflict_rows = [bar(f"conflicting_duplicate:{part}", part) for part in ("first", "second")]
    late_delivery_row, _, late_delivery = bar("out_of_order_delivery:late", "delivered_late")
    _, _, next_delivery = bar("out_of_order_delivery:next", "next_session_delivered_first")
    unknown_row, _, unknown = bar("unknown_instrument", "unknown_instrument")
    _, _, listing_first = bar("mid_period_listing:first", "first_bar")
    _, _, delisting_last = bar("delisting:last", "last_bar")
    _, _, rename_before = bar("ticker_rename:before", "last_bar_before_rename")
    _, _, rename_after = bar("ticker_rename:after", "first_bar_after_rename")
    _, split_before_bar, split_before = bar("unsupported_split:before", "last_bar_before_ex_date")
    _, split_bar, split_ex = bar("unsupported_split:ex_date", "ex_date_bar")
    _, _, stale_last = bar("stale_tail:last", "last_bar")

    listed = instrument_id(LISTED_MID_PERIOD)
    delisted = instrument_id(DELISTED)
    renamed = instrument_id(RENAMED)
    split = instrument_id(SPLIT)
    return [
        _scenario(
            "late_revision",
            "LATE_REVISION",
            [BARS_FILE],
            instrument_id(LATE_REVISION[0]),
            sessions[LATE_REVISION[1]],
            "A final bar is corrected by revision 2, published three sessions later with a "
            "different close, high/low envelope and volume.",
            "SUPERSEDE_FROM_AVAILABLE_AT",
            "Knowledge cutoffs before revision 2's available_at see revision 1; later cutoffs see "
            "revision 2. Snapshots built before the correction keep revision 1.",
            [late_row, revised_row],
            [late_original, late_revised],
            {"revision_lag_sessions": LATE_REVISION_LAG},
        ),
        _scenario(
            "provisional_then_final",
            "PROVISIONAL_BAR",
            [BARS_FILE],
            instrument_id(PROVISIONAL[0]),
            sessions[PROVISIONAL[1]],
            "A provisional bar (final=false) is published one minute after the close. The final "
            "bar (revision 2) follows before the next session's open.",
            "EXCLUDE_PROVISIONAL_UNTIL_FINAL",
            "The provisional revision never enters close-based features. At the regular cutoff "
            "(close plus 15 minutes) the session has no completed bar; revision 2 is eligible "
            "from its available_at.",
            [prov_row, final_row],
            [provisional, final],
            {"final_published_before_session": sessions[PROVISIONAL[1] + 1].isoformat()},
        ),
        _scenario(
            "missing_session",
            "MISSING_SESSION",
            [BARS_FILE],
            instrument_id(MISSING_SESSION[0]),
            sessions[MISSING_SESSION[1]],
            "No record exists for one calendar session in the middle of an active instrument's "
            "history.",
            "EXPLICIT_GAP_NO_FILL",
            "Completeness checks report the gap. Features that need the session are NOT_READY or "
            "flagged; the gap is never forward-filled or zero-filled.",
            [],
            [missing_previous, missing_next],
            {
                "previous_session": sessions[MISSING_SESSION[1] - 1].isoformat(),
                "next_session": sessions[MISSING_SESSION[1] + 1].isoformat(),
            },
        ),
        _scenario(
            "impossible_ohlc",
            "IMPOSSIBLE_OHLC",
            [BARS_FILE],
            instrument_id(IMPOSSIBLE_OHLC[0]),
            sessions[IMPOSSIBLE_OHLC[1]],
            "The only record for the session has high below low (the two values are swapped).",
            "QUARANTINE_INVALID_OHLC",
            "Quarantine the record. The session has no valid bar for this instrument.",
            [impossible_row],
            [impossible],
            {},
        ),
        _scenario(
            "identical_duplicate",
            "IDENTICAL_DUPLICATE",
            [BARS_FILE],
            instrument_id(IDENTICAL_DUPLICATE[0]),
            sessions[IDENTICAL_DUPLICATE[1]],
            "The same record (identity, revision and payload) is delivered twice in one batch, "
            "not on adjacent rows.",
            "DEDUPLICATE_IDEMPOTENT",
            "Store one observation and count the redelivery in duplicate-rate quality metrics.",
            [row for row, _, _ in identical_rows],
            [record for _, _, record in identical_rows],
            {},
        ),
        _scenario(
            "conflicting_duplicate",
            "CONFLICTING_DUPLICATE",
            [BARS_FILE],
            instrument_id(CONFLICTING_DUPLICATE[0]),
            sessions[CONFLICTING_DUPLICATE[1]],
            "Two records share provider_record_id, revision and timestamps but differ in close "
            "and volume.",
            "QUARANTINE_IDENTITY_CONFLICT",
            "Quarantine both copies and raise a quality incident. Neither copy enters features; "
            "the session stays unresolved until a new revision arrives. Never pick one silently.",
            [row for row, _, _ in conflict_rows],
            [record for _, _, record in conflict_rows],
            {"differing_columns": ["close", "volume"]},
        ),
        _scenario(
            "out_of_order_delivery",
            "OUT_OF_ORDER_DELIVERY",
            [BARS_FILE],
            instrument_id(OUT_OF_ORDER[0]),
            sessions[OUT_OF_ORDER[1]],
            "A session's bar is delivered after the next session's bar for the same instrument, "
            "20 minutes after that later session's close.",
            "ORDER_BY_EVENT_TIME",
            "Accept the record and order the series by interval_start, not delivery position. It "
            "is eligible only from its available_at; earlier cutoffs see a gap for the session.",
            [late_delivery_row],
            [late_delivery, next_delivery],
            {"delivered_after_session": sessions[OUT_OF_ORDER[1] + 1].isoformat()},
        ),
        _scenario(
            "unknown_instrument",
            "UNKNOWN_INSTRUMENT",
            [BARS_FILE],
            instrument_id(UNKNOWN_INSTRUMENT[0]),
            sessions[UNKNOWN_INSTRUMENT[1]],
            "A well-formed bar references an instrument ID that no reference file defines.",
            "QUARANTINE_UNKNOWN_INSTRUMENT",
            "Reject the record until the identity is resolved. Never create an instrument "
            "implicitly or map it by guesswork.",
            [unknown_row],
            [unknown],
            {},
        ),
        _scenario(
            "mid_period_listing",
            "MID_PERIOD_LISTING",
            [INSTRUMENTS_FILE, SYMBOLS_FILE, UNIVERSE_FILE, BARS_FILE],
            listed,
            sessions[LISTING_SESSION],
            "An instrument lists partway through the window. Its reference records are announced "
            "four sessions earlier.",
            "NO_HISTORY_BEFORE_LISTING",
            "The instrument is unknown before its notice, joins the universe on its first session "
            "and has no earlier bars. Features stay NOT_READY until their warm-up is met by "
            "post-listing sessions; nothing is back-filled.",
            [],
            [
                reference(
                    INSTRUMENTS_FILE,
                    instrument_rows,
                    INSTRUMENT_COLUMNS,
                    "instrument",
                    instrument_id=listed,
                ),
                reference(
                    SYMBOLS_FILE,
                    symbol_rows,
                    SYMBOL_COLUMNS,
                    "listing_symbol",
                    instrument_id=listed,
                ),
                reference(
                    UNIVERSE_FILE,
                    universe_rows,
                    UNIVERSE_COLUMNS,
                    "universe_add",
                    instrument_id=listed,
                ),
                listing_first,
            ],
            {
                "listed_on": sessions[LISTING_SESSION].isoformat(),
                "notice_available_at": _instant(_notice(sessions[LISTING_NOTICE_SESSION])),
                "sessions_listed": SESSION_COUNT - LISTING_SESSION,
                "first_session_with_full_warm_up": sessions[
                    LISTING_SESSION + WARM_UP_SESSIONS - 1
                ].isoformat(),
            },
        ),
        _scenario(
            "delisting_retained_in_history",
            "DELISTING",
            [UNIVERSE_FILE, BARS_FILE],
            delisted,
            sessions[DELISTING_LAST_SESSION],
            "An instrument declines and is delisted. Its last session is the one shown; the "
            "universe removal takes effect on the next session and was announced five sessions "
            "before the last one.",
            "RETAIN_DELISTED_IN_HISTORY",
            "The instrument is a universe member for every as-of date through its last session. "
            "Historical universes and backtests must include it (no survivorship bias). No bar "
            "after the removal is expected, so its absence is not staleness.",
            [],
            [
                reference(
                    UNIVERSE_FILE,
                    universe_rows,
                    UNIVERSE_COLUMNS,
                    "universe_remove",
                    instrument_id=delisted,
                    action="REMOVE",
                ),
                delisting_last,
            ],
            {
                "last_session": sessions[DELISTING_LAST_SESSION].isoformat(),
                "removed_from": sessions[DELISTING_LAST_SESSION + 1].isoformat(),
                "notice_available_at": _instant(_notice(sessions[DELISTING_NOTICE_SESSION])),
            },
        ),
        _scenario(
            "ticker_rename",
            "TICKER_RENAME",
            [SYMBOLS_FILE, BARS_FILE],
            renamed,
            sessions[RENAME_SESSION],
            f"SYN{RENAMED:02d} trades as {RENAMED_SYMBOL} from the session shown. The change was "
            "announced five sessions earlier, which is also when the old period's effective_to "
            "became known. The instrument ID does not change.",
            "RESOLVE_SYMBOL_AS_OF",
            "Resolve symbols by effective period and available_at with as_of <= knowledge_cutoff. "
            "The bar series continues under the same instrument_id across the rename.",
            [],
            [
                reference(
                    SYMBOLS_FILE,
                    symbol_rows,
                    SYMBOL_COLUMNS,
                    "old_symbol",
                    instrument_id=renamed,
                    reason="LISTING",
                ),
                reference(
                    SYMBOLS_FILE,
                    symbol_rows,
                    SYMBOL_COLUMNS,
                    "new_symbol",
                    instrument_id=renamed,
                    reason="RENAME",
                ),
                rename_before,
                rename_after,
            ],
            {
                "old_symbol": f"SYN{RENAMED:02d}",
                "new_symbol": RENAMED_SYMBOL,
                "effective_from": sessions[RENAME_SESSION].isoformat(),
                "notice_available_at": _instant(_notice(sessions[RENAME_NOTICE_SESSION])),
            },
        ),
        _scenario(
            "unsupported_split",
            "UNSUPPORTED_CORPORATE_ACTION",
            [ACTIONS_FILE, BARS_FILE],
            split,
            sessions[SPLIT_SESSION],
            "A 2-for-1 split takes effect on the ex-date. Bars are unadjusted, so raw prices "
            "halve and volume roughly doubles from the ex-date.",
            "INVALID_UNSUPPORTED_CORPORATE_ACTION",
            "Aura has no corporate-action adjustment yet. Features whose window spans the "
            "ex-date are INVALID, or the instrument is excluded; the raw step is never read as a "
            "return. The instrument cannot supply qualification evidence (AC-20).",
            [],
            [
                reference(
                    ACTIONS_FILE, action_rows, ACTION_COLUMNS, "split", action_id=SPLIT_ACTION_ID
                ),
                split_before,
                split_ex,
            ],
            {
                "action_id": SPLIT_ACTION_ID,
                "ratio_new": 2,
                "ratio_old": 1,
                "ex_date": sessions[SPLIT_SESSION].isoformat(),
                "notice_available_at": _instant(_notice(sessions[SPLIT_NOTICE_SESSION])),
                "raw_close_before_ex_date": _price(split_before_bar.close),
                "raw_open_on_ex_date": _price(split_bar.open),
            },
        ),
        _scenario(
            "stale_tail",
            "STALE_TAIL",
            [BARS_FILE],
            instrument_id(STALE),
            sessions[STALE_LAST_SESSION],
            "Bars stop before the end of the window without any delisting, removal or "
            "corporate action. The session shown is the last bar.",
            "FLAG_STALE_NO_FORWARD_FILL",
            "Freshness checks mark the instrument stale for later as-of dates. It stays a "
            "universe member, and its last close is never forward-filled.",
            [],
            [stale_last],
            {
                "last_bar_session": sessions[STALE_LAST_SESSION].isoformat(),
                "missing_trailing_sessions": SESSION_COUNT - 1 - STALE_LAST_SESSION,
                "dataset_last_session": sessions[-1].isoformat(),
            },
        ),
    ]


FILE_LAYOUT: Final = {
    INSTRUMENTS_FILE: (INSTRUMENT_COLUMNS, ("instrument_id",), "instrument_id"),
    SYMBOLS_FILE: (
        SYMBOL_COLUMNS,
        ("instrument_id", "effective_from"),
        "instrument_id, effective_from",
    ),
    UNIVERSE_FILE: (
        UNIVERSE_COLUMNS,
        ("universe_id", "instrument_id", "action", "effective_from"),
        "available_at, instrument_id",
    ),
    BARS_FILE: (
        BAR_COLUMNS,
        ("provider_record_id", "revision"),
        "delivery order: non-decreasing available_at; within one publication batch by "
        "instrument_id, with redeliveries after the batch",
    ),
    ACTIONS_FILE: (ACTION_COLUMNS, ("action_id",), "available_at, action_id"),
}


def _digest(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def _records(content: bytes) -> int:
    return content.count(b"\n") - 1


def _file_details(files: dict[str, bytes]) -> JSON:
    details: JSON = {}
    for name in DATA_FILES:
        columns, identity, order = FILE_LAYOUT[name]
        details[name] = {
            "media_type": "text/csv",
            "bytes": len(files[name]),
            "row_unit": "CSV record excluding the header",
            "identity": list(identity),
            "row_order": order,
            "columns": [{"name": column, "description": text} for column, text in columns],
        }
    details[README_FILE] = {
        "media_type": "text/markdown",
        "bytes": len(files[README_FILE]),
        "row_unit": "text line",
    }
    return details


def _range(values: Sequence[str]) -> JSON:
    return {"min": min(values), "max": max(values)}


def _dst_transitions(sessions: Sequence[date]) -> list[JSON]:
    transitions: list[JSON] = []
    for year in range(sessions[0].year, sessions[-1].year + 1):
        for change, offset in zip(dst_period(year), ("-04:00", "-05:00"), strict=True):
            if sessions[0] < change < sessions[-1]:
                after = next(s for s in sessions if s > change)
                transitions.append(
                    {
                        "date": change.isoformat(),
                        "utc_offset_after": offset,
                        "first_session_after": after.isoformat(),
                        "interval_start_utc_after": _instant(new_york_to_utc(after, SESSION_OPEN)),
                    }
                )
    return transitions


def _segments_json(sessions: Sequence[date]) -> list[JSON]:
    result: list[JSON] = []
    start = 0
    for number, segment in enumerate(SEGMENTS, start=1):
        end = start + segment.sessions - 1
        result.append(
            {
                "segment": number,
                "kind": segment.kind,
                "first_session": sessions[start].isoformat(),
                "last_session": sessions[end].isoformat(),
                "sessions": segment.sessions,
                "market_drift": str(segment.drift),
                "market_volatility": str(segment.volatility),
                "reversion": str(segment.reversion),
                "sector_volatility": str(segment.sector_volatility),
                "sector_drift_spread": str(segment.sector_spread),
                "idiosyncratic_scale": str(segment.idiosyncratic_scale),
                "volume_factor": str(segment.volume_factor),
            }
        )
        start = end + 1
    return result


def _series(items: Sequence[str]) -> str:
    return items[0] if len(items) == 1 else ", ".join(items[:-1]) + " and " + items[-1]


def _table(header: Sequence[str], align: Sequence[str], body: Sequence[Sequence[object]]) -> str:
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join(align) + "|"]
    lines.extend("| " + " | ".join(str(cell) for cell in row) + " |" for row in body)
    return "\n".join(lines)


def _readme(build: _Build, files: dict[str, bytes], scenarios: Sequence[JSON]) -> bytes:
    """Dataset README: one line per paragraph, derived from the same constants as the data."""
    sessions = build.sessions
    delay = int(PUBLICATION_DELAY.total_seconds() // 60)

    def rows(name: str) -> int:
        return files[name].count(b"\n") - 1

    def coverage(spec: InstrumentSpec) -> str:
        active = _active_sessions(spec)
        first, last = sessions[active.start], sessions[active.stop - 1]
        if spec.number == LISTED_MID_PERIOD:
            return f"lists {first}"
        if spec.number == DELISTED:
            return f"last session {last}, then delisted"
        if spec.number == STALE:
            return f"bars stop after {last} (stale tail)"
        return "whole window"

    def symbols(spec: InstrumentSpec) -> str:
        if spec.number == RENAMED:
            return f"{spec.symbol}; {RENAMED_SYMBOL} from {sessions[RENAME_SESSION]}"
        return spec.symbol

    files_table = _table(
        ("File", "Rows", "Contents"),
        ("---", "---:", "---"),
        [
            (f"`{INSTRUMENTS_FILE}`", rows(INSTRUMENTS_FILE), "Stable IDs and static attributes"),
            (f"`{SYMBOLS_FILE}`", rows(SYMBOLS_FILE), "Effective-dated symbol assignments"),
            (
                f"`{UNIVERSE_FILE}`",
                rows(UNIVERSE_FILE),
                f"Point-in-time ADD/REMOVE events for `{UNIVERSE_ID}`",
            ),
            (f"`{BARS_FILE}`", rows(BARS_FILE), "Unadjusted daily bars in delivery order"),
            (f"`{ACTIONS_FILE}`", rows(ACTIONS_FILE), "Corporate actions"),
            (
                f"`{MANIFEST_FILE}`",
                "n/a",
                "Hashes, row counts, columns, time ranges, calendar, scenarios, rights",
            ),
        ],
    )
    instruments_table = _table(
        ("ID", "Symbols", "Type", "Sector", "Coverage"),
        ("---",) * 5,
        [
            (
                f"`{spec.instrument_id}`",
                symbols(spec),
                spec.security_type,
                spec.sector,
                coverage(spec),
            )
            for spec in INSTRUMENTS
        ],
    )
    segments_table = _table(
        ("#", "Kind", "First session", "Last session", "Sessions", "Drift", "Volatility"),
        ("---:", "---", "---", "---", "---:", "---:", "---:"),
        [
            (
                s["segment"],
                s["kind"],
                s["first_session"],
                s["last_session"],
                s["sessions"],
                s["market_drift"],
                s["market_volatility"],
            )
            for s in _segments_json(sessions)
        ],
    )
    traps_table = _table(
        ("Scenario", "Instrument", "Session", "Expected handling"),
        ("---",) * 4,
        [
            (
                f"`{s['id']}`",
                f"`{s['instrument_id']}`",
                s["session_date"],
                f"`{s['expected_handling']}`",
            )
            for s in scenarios
        ],
    )
    transitions = _series([str(t["date"]) for t in _dst_transitions(sessions)])
    holidays = ", ".join(day.isoformat() for day in FIXTURE_HOLIDAYS)
    time_semantics = "\n".join(
        (
            "- Instants are UTC in RFC 3339 form with a `Z` suffix. Dates are America/New_York "
            "session dates.",
            "- A daily bar covers 09:30 to 16:00 America/New_York. `interval_start` and "
            "`interval_end` store those instants in UTC, so they move by an hour across "
            "daylight-saving changes: 14:30Z to 21:00Z under EST, 13:30Z to 20:00Z under EDT. "
            f"The window crosses the changes on {transitions}.",
            "- `interval_end` is the bar's event time. `available_at` is `interval_end` plus the "
            f"declared {delay}-minute publication delay unless a scenario says otherwise. "
            "Point-in-time readers must require `event_time <= as_of` and "
            "`available_at <= knowledge_cutoff`.",
            "- Reference records carry their own `available_at`: 08:00 New York for records "
            "known before trading, 17:00 New York for notices published after the close. "
            f"`{UNIVERSE_FILE}` is an append-only event log: a row takes effect from its "
            "`effective_from` and is known from its `available_at`.",
            f"- `{SYMBOLS_FILE}` periods run from `effective_from` (inclusive) to `effective_to` "
            "(exclusive, empty while open) and never overlap. The end of a period becomes known "
            "with the `available_at` of the row that replaces it, so resolve symbols with "
            "`as_of <= knowledge_cutoff`.",
            f"- `{BARS_FILE}` rows are in delivery order, which never decreases in "
            "`available_at`. Delivery order is not event order. `provider_record_id` plus "
            "`revision` identifies an observation.",
            "- Prices are unadjusted USD on a $0.01 tick with exactly two decimal places. Volume "
            "is an integer number of shares.",
        )
    )
    blocks = (
        "# Synthetic US equities fixture v1",
        "> **SYNTHETIC FIXTURE. NOT MARKET DATA.** Every instrument, price, volume and event in "
        f"this directory was generated by `{GENERATOR_MODULE}` from a fixed seed. None of it "
        "describes a real security, company, exchange or market. Do not treat it as evidence "
        "about markets, strategies or models, and never use it as qualification evidence. The "
        f"provenance class is `{PROVENANCE_CLASS}` and `{MANIFEST_FILE}` declares "
        "`not_market_data: true`.",
        "The decision and its limits are recorded in "
        "[ADR-0024](../../../../docs/adr/0024-synthetic-fixture-market-data.md).",
        "## Regenerate and verify",
        f"```powershell\nuv run python -m {GENERATOR_MODULE} --out {DEFAULT_OUT}\n"
        f"uv run pytest {TEST_MODULE}\n```",
        "Regeneration is byte-identical. The generator uses integer SplitMix64 draws (seed "
        f"{SEED}), `Decimal` arithmetic under a pinned context, LF line endings and float-free "
        "formatting. `.gitattributes` turns off line-ending conversion under `data/fixtures/`. "
        "The tests regenerate the dataset into a temporary folder and compare SHA-256 hashes "
        f"with these files and with `{MANIFEST_FILE}`. Any change to the generated bytes needs "
        "a new dataset version in a new directory; v1 is immutable.",
        "## Files",
        files_table,
        "Rows are CSV records excluding the header. Files are ASCII with LF line endings. No "
        "cell is quoted, and only `effective_to` is ever empty. "
        f"`{MANIFEST_FILE}` describes every column.",
        "## Instruments",
        instruments_table,
        "Symbols start with `SYN` and always contain a digit. US exchange tickers are letters "
        "only, with an optional share-class suffix, so no fixture symbol can collide with a real "
        "ticker. All names and sectors are fictional. "
        f"`{instrument_id(UNKNOWN_INSTRUMENT[0])}` appears only as the unknown-instrument trap "
        "and is deliberately absent from the reference files.",
        "## Time semantics",
        time_semantics,
        f"## Calendar `{CALENDAR_ID}`",
        f"Weekdays from {sessions[0]} to {sessions[-1]} minus the declared fixture holidays, "
        f"{len(sessions)} sessions in all. **This is not an exchange calendar.** It has no early "
        "closes, no unscheduled closures and no exchange rules; every session runs 09:30 to "
        f"16:00 New York time. Fixture holidays: {holidays}.",
        f"A {WARM_UP_SESSIONS}-session warm-up is complete on "
        f"{sessions[WARM_UP_SESSIONS - 1]} for instruments that cover the whole window.",
        "## Price process",
        "A seeded regime-switching random walk. Each session's market return is "
        "`drift + volatility * z`; range-bound segments also pull the market level back toward "
        "its level at the start of the segment. An instrument's return is beta times the "
        "market return plus a fictional-sector factor and idiosyncratic noise. `z` is an "
        "Irwin-Hall approximation to a standard normal: twelve 53-bit uniforms minus 6. Open, "
        "high and low come from seeded gap and range draws. High rounds up and low rounds down "
        "to the tick, so every generated bar keeps `low <= open, close <= high`.",
        "The segments below are generator parameters for tests. They are **not** regime "
        "classifications and must not be used as labels for the Regime Engine. Drift and "
        "volatility are the daily market-factor parameters.",
        segments_table,
        "## Traps",
        traps_table,
        f"`{MANIFEST_FILE}` gives each scenario's rows, facts, full expectation and covering "
        "test. Bar rows outside every scenario's `trap_rows` are valid, final, first-revision "
        f"bars published at the close plus {delay} minutes.",
        "## Rights",
        "MIT license (repository). No third-party content. Generated entirely from code in this "
        "repository.",
    )
    return ("\n\n".join(blocks) + "\n").encode("ascii")


def _manifest(build: _Build, files: dict[str, bytes], scenarios: Sequence[JSON]) -> bytes:
    sessions = build.sessions
    bars = [d.bar for d in build.deliveries]
    reference_available: list[str] = []
    reference_dates: list[str] = []
    for rows, date_columns, available_column in (
        (_instrument_rows(sessions), (6,), 7),
        (_symbol_rows(sessions), (2, 3), 5),
        (_universe_rows(sessions), (3,), 5),
        (_action_rows(sessions), (3,), 6),
    ):
        reference_dates.extend(row[c] for row in rows for c in date_columns if row[c])
        reference_available.extend(row[available_column] for row in rows)
    readme = files[README_FILE]
    manifest: JSON = {
        "manifest_schema_version": MANIFEST_SCHEMA_VERSION,
        "dataset_id": DATASET_ID,
        "version": DATASET_VERSION,
        "title": "Synthetic US equities fixture v1 (NOT MARKET DATA)",
        "description": (
            "Fictional instruments and generated prices for testing Aura's data, feature and "
            "regime code. Not market data, not investment evidence, not qualification evidence."
        ),
        "rights": {
            "license": "MIT (repo)",
            "third_party_content": "none",
            "provenance_class": PROVENANCE_CLASS,
            "not_market_data": True,
        },
        "generator": {
            "module": GENERATOR_MODULE,
            "version": GENERATOR_VERSION,
            "seed": SEED,
            "prng": "SPLITMIX64",
            "normal_approximation": "IRWIN_HALL_12",
            "decimal_context": {"precision": 28, "rounding": "ROUND_HALF_EVEN"},
            "command": f"uv run python -m {GENERATOR_MODULE} --out {DEFAULT_OUT}",
        },
        "publisher": {
            "id": PUBLISHER_ID,
            "kind": PROVENANCE_CLASS,
            "availability": (
                "available_at is the publication time declared by this generator, which is the "
                "publisher. It is authoritative for this fixture and meaningless for any real "
                "market."
            ),
        },
        "calendar": CALENDAR_ID,
        "calendar_definition": {
            "id": CALENDAR_ID,
            "exchange_calendar": False,
            "definition": (
                "Monday to Friday minus the declared fixture holidays. Every session runs 09:30 "
                "to 16:00 America/New_York. No early closes, unscheduled closures or exchange "
                "rules are modelled."
            ),
            "timezone": TIMEZONE,
            "session_open_local": SESSION_OPEN.strftime("%H:%M"),
            "session_close_local": SESSION_CLOSE.strftime("%H:%M"),
            "first_session": sessions[0].isoformat(),
            "last_session": sessions[-1].isoformat(),
            "sessions": len(sessions),
            "holidays": [day.isoformat() for day in FIXTURE_HOLIDAYS],
            "dst_rule": (
                "US rule in force since 2007: UTC-04:00 from the second Sunday in March to the "
                "first Sunday in November, UTC-05:00 otherwise"
            ),
            "dst_transitions": _dst_transitions(sessions),
        },
        "time_semantics": {
            "instant_format": "RFC 3339 UTC with Z suffix, second precision",
            "date_format": "ISO 8601 calendar date (America/New_York session date)",
            "bar_interval": "1d",
            "bar_event_time": "interval_end",
            "publication_delay": f"PT{int(PUBLICATION_DELAY.total_seconds() // 60)}M",
            "bar_available_at": (
                "interval_end + publication_delay unless a scenario declares otherwise"
            ),
            "published_at": "equal to available_at",
            "reference_available_at": (
                "08:00 America/New_York for records known before trading; 17:00 "
                "America/New_York for post-close notices"
            ),
            "symbol_periods": (
                "[effective_from, effective_to), never overlapping. A period's end becomes known "
                "with the available_at of the row that replaces it; resolve with "
                "as_of <= knowledge_cutoff."
            ),
            "point_in_time_rule": "event_time <= as_of and available_at <= knowledge_cutoff",
        },
        "bar_conventions": {
            "currency": "USD",
            "adjustment_basis": ADJUSTMENT_BASIS,
            "adjustment_meaning": "prices as traded (unadjusted): no split or dividend adjustment",
            "tick_size": str(TICK),
            "price_format": "decimal string with exactly two fractional digits",
            "volume_unit": "shares",
            "identity": "provider_record_id + revision",
        },
        "warm_up": {
            "sessions": WARM_UP_SESSIONS,
            "first_session_with_full_warm_up": sessions[WARM_UP_SESSIONS - 1].isoformat(),
            "sessions_with_full_warm_up": len(sessions) - WARM_UP_SESSIONS + 1,
            "applies_to": "instruments covering the whole window",
        },
        "instruments": {
            "count": len(INSTRUMENTS),
            "equities": sum(1 for spec in INSTRUMENTS if spec.security_type == "EQUITY"),
            "etfs": sum(1 for spec in INSTRUMENTS if spec.security_type == "ETF"),
            "id_rule": "inst_syn_ followed by four digits",
            "symbol_rule": (
                "SYN followed by two characters, at least one a digit. US exchange tickers are "
                "letters only, so fixture symbols cannot collide with real tickers."
            ),
            "universe_id": UNIVERSE_ID,
            "unknown_instrument_ids": [instrument_id(UNKNOWN_INSTRUMENT[0])],
        },
        "files": {
            name: {"sha256": _digest(files[name]), "rows": _records(files[name])}
            for name in DATA_FILES
        },
        "documents": {README_FILE: {"sha256": _digest(readme), "rows": readme.count(b"\n")}},
        "file_details": _file_details(files),
        "manifest_digest": (
            "not recorded: a manifest cannot contain its own hash; verify it by regeneration"
        ),
        "event_range": {
            "min": _instant(min(bar.interval_start for bar in bars)),
            "max": _instant(max(bar.interval_end for bar in bars)),
            "basis": f"{BARS_FILE}: earliest interval_start to latest interval_end",
        },
        "availability_range": {
            "min": _instant(min(bar.available_at for bar in bars)),
            "max": _instant(max(bar.available_at for bar in bars)),
            "basis": f"{BARS_FILE}: available_at",
        },
        "reference_ranges": {
            "effective_dates": _range(reference_dates),
            "available_at": _range(reference_available),
            "basis": "listing, effective and ex dates and available_at of the reference files",
        },
        "stats": {
            "sessions": len(sessions),
            "instruments": len(INSTRUMENTS),
            "bar_rows": len(bars),
            "data_rows": sum(_records(files[name]) for name in DATA_FILES),
            "data_bytes": sum(len(files[name]) for name in DATA_FILES),
        },
        "process": {
            "model": "SEEDED_REGIME_SWITCHING_RANDOM_WALK_V1",
            "note": (
                "Segments are data-generating parameters for tests. They are not canonical "
                "regime classifications and must not label the Regime Engine."
            ),
            "market_return": (
                "drift + volatility * z; RANGE_BOUND subtracts reversion * "
                "(level / segment_start_level - 1)"
            ),
            "instrument_return": (
                "beta * market + sector factor + idiosyncratic volatility * idiosyncratic_scale * z"
            ),
            "segments": _segments_json(sessions),
        },
        "scenario_conventions": {
            "row": "1-based CSV record number in the named file, excluding the header",
            "trap_rows": (
                f"{BARS_FILE} rows that are deliberately invalid, duplicated, revised, "
                "provisional, delayed or unidentifiable. Every other bar row is a valid, final, "
                "first-revision bar published at interval_end + publication_delay."
            ),
            "records": "rows the scenario refers to, with every value exactly as in the file",
            "covered_by": "pytest node that checks the scenario is present exactly as declared",
        },
        "scenarios": list(scenarios),
    }
    return (json.dumps(manifest, indent=2, ensure_ascii=True) + "\n").encode("ascii")


def build_dataset() -> dict[str, bytes]:
    """Return every dataset file keyed by name. Pure: no clock, filesystem or environment."""
    with localcontext(_decimal_context()):
        sessions = fixture_sessions()
        segments = _segment_by_session()
        market, sectors = _factor_returns()
        clean = {
            spec.number: _simulate(
                spec, _active_sessions(spec), sessions, segments, market, sectors
            )
            for spec in INSTRUMENTS
        }
        unknown_day = range(UNKNOWN_INSTRUMENT[1], UNKNOWN_INSTRUMENT[1] + 1)
        (unknown,) = _simulate(UNKNOWN_SPEC, unknown_day, sessions, segments, market, sectors)
        build = _deliveries(clean, unknown, sessions)
        files: dict[str, bytes] = {
            INSTRUMENTS_FILE: _csv(INSTRUMENT_COLUMNS, _instrument_rows(sessions)),
            SYMBOLS_FILE: _csv(SYMBOL_COLUMNS, _symbol_rows(sessions)),
            UNIVERSE_FILE: _csv(UNIVERSE_COLUMNS, _universe_rows(sessions)),
            BARS_FILE: _csv(BAR_COLUMNS, [d.bar.cells() for d in build.deliveries]),
            ACTIONS_FILE: _csv(ACTION_COLUMNS, _action_rows(sessions)),
        }
        scenarios = _scenarios(build)
        files[README_FILE] = _readme(build, files, scenarios)
        files[MANIFEST_FILE] = _manifest(build, files, scenarios)
    return files


def write_dataset(out: Path) -> dict[str, bytes]:
    files = build_dataset()
    out.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        (out / name).write_bytes(content)
    return files


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog=f"python -m {GENERATOR_MODULE}",
        description=f"Write the {DATASET_ID} synthetic fixture (NOT market data).",
    )
    parser.add_argument("--out", required=True, type=Path, help="Directory to write into")
    args = parser.parse_args(argv)
    out: Path = args.out
    for name, content in write_dataset(out).items():
        digest = hashlib.sha256(content).hexdigest()
        print(f"{name}: {len(content)} bytes sha256={digest}")
    print(f"Wrote {DATASET_ID} ({PROVENANCE_CLASS}, not market data) to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
